openapi: 3.0.0
info:
  title: Reconciliation and Settlement Framework (RSF) for ONDC
  description: ONDC  Reconciliation and Settlement Framework API Specification
  version: 2.0.0
security:
  - SubscriberAuth: []
paths:
  /settle:
    post:
      tags:
        - Collector
        - Receiver
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                context:
                  $ref: '#/components/schemas/Context'
                message:
                  type: object
                  properties:
                    collector_app_id:
                      type: string
                    receiver_app_id:
                      type: string
                    settlement:
                      $ref: '#/components/schemas/Settlement'
              required:
                - context
                - message
      responses:
        '200':
          description: Acknowledgement of message received
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      ack:
                        $ref: '#/components/schemas/Ack'
                    required:
                      - ack
                  error:
                    $ref: '#/components/schemas/Error'
                required:
                  - message
  /on_settle:
    post:
      tags:
        - Collector
        - Receiver
      requestBody:
        description: SA responds with /on_settle
        content:
          application/json:
            schema:
              type: object
              properties:
                context:
                  $ref: '#/components/schemas/Context'
                message:
                  type: object
                  properties:
                    collector_app_id:
                      type: string
                    receiver_app_id:
                      type: string
                    settlement:
                      $ref: '#/components/schemas/Settlement'
                  required:
                    - settlement
                error:
                  $ref: '#/components/schemas/Error'
              required:
                - context
                - message
      responses:
        '200':
          description: Acknowledgement of message received
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      ack:
                        $ref: '#/components/schemas/Ack'
                    required:
                      - ack
                  error:
                    $ref: '#/components/schemas/Error'
                required:
                  - message
components:
  securitySchemes:
    SubscriberAuth:
      type: apiKey
      in: header
      name: Authorization
      description: >-
        Signature of message body using Collector or Receiver subscriber's
        signing public key. <br/><br/>Format:<br/><br/><code>Authorization :
        Signature
        keyId="{subscriber_id}|{unique_key_id}|{algorithm}",algorithm="ed25519",created="1606970629",expires="1607030629",headers="(created)
        (expires) digest",signature="Base64(signing string)"</code>
  schemas:
    Ack:
      description: Describes the ACK response
      type: object
      properties:
        status:
          type: string
          description: >-
            Describe the status of the ACK response. If schema validation
            passes, status is ACK else it is NACK
          enum:
            - ACK
            - NACK
    Amount:
      type: object
      properties:
        currency:
          type: string
          example: INR
        value:
          type: string
          example: ''
    BankDetails:
      type: object
      properties:
        account_no:
          type: string
          example: ''
        ifsc_code:
          type: string
          example: ''
    Context:
      description: Describes a beckn message context
      type: object
      properties:
        domain:
          type: string
        location:
          type: object
          properties:
            country:
              type: object
              properties:
                code:
                  type: string
                  example: IND
            city:
              type: object
              properties:
                code:
                  type: string
                  example: '*'
        action:
          type: string
          description: >-
            Defines the Beckn API call. Any actions other than the enumerated
            actions are not supported by Beckn Protocol
        version:
          type: string
          description: Version of Beckn core API specification being used
        bap_id:
          type: string
          description: >-
            Unique id of the BAP. By default it is the fully qualified domain
            name of the BAP
        bap_uri:
          type: string
          format: uri
          description: >-
            URI of the BAP for accepting callbacks. Must have the same domain
            name as the bap_id
        bpp_id:
          type: string
          description: >-
            Unique id of the BPP. By default it is the fully qualified domain
            name of the BPP
        bpp_uri:
          type: string
          format: uri
          description: URI of the BPP. Must have the same domain name as the bap_id
        transaction_id:
          type: string
          description: >-
            This is a unique value which persists across all API calls from
            search through confirm
        message_id:
          type: string
          description: >-
            This is a unique value which persists during a request / callback
            cycle
        timestamp:
          type: string
          format: date-time
          description: Time of request generation in RFC3339 format
        key:
          type: string
          description: The encryption public key of the sender
        ttl:
          type: string
          description: >-
            The duration in ISO8601 format after timestamp for which this
            message holds valid
      required:
        - domain
        - action
        - location
        - version
        - transaction_id
        - message_id
        - bap_id
        - bap_uri
        - timestamp
    Error:
      description: >-
        Describes an error object that is returned by a Collector or Receiver as
        a response or callback to an action by another network participant. This
        object is sent when any request received by a network participant is
        unacceptable. This object can be sent either during Ack or with the
        callback.
      type: object
      properties:
        code:
          type: string
          description: Standard error code. For full list of error codes, refer to TBD
        message:
          type: string
          description: >-
            Human readable message describing the error. Used mainly for
            logging. Not recommended to be shown to the user.
    Orders:
      type: array
      items:
        type: object
        properties:
          id:
            description: Describes the order id
            type: string
          inter_participant:
            description: >-
              Provides details about the settlement amount, payable/ receivable
              and status between the Collector and the Receiver
            type: object
            properties:
              amount:
                $ref: '#/components/schemas/Amount'
              status:
                type: string
                enum:
                  - SETTLED
                  - NOT-SETTLED
              reference_no:
                type: string
              error:
                $ref: '#/components/schemas/Error'
          collector:
            description: Provides details about the amount to be retained by the collector
            type: object
            properties:
              amount:
                $ref: '#/components/schemas/Amount'
          provider:
            description: >-
              Provides details about the amount to be settled to the Provider of
              an NP.
            type: object
            properties:
              id:
                type: string
                example: ''
              name:
                type: string
                example: ''
              bank_details:
                $ref: '#/components/schemas/BankDetails'
              status:
                type: string
                enum:
                  - SETTLED
                  - NOT-SETTLED
              amount:
                $ref: '#/components/schemas/Amount'
              reference_no:
                type: string
              error:
                $ref: '#/components/schemas/Error'
          self:
            type: object
            description: >-
              Provides details about the amount for the NP to move to their
              operative account
            properties:
              amount:
                $ref: '#/components/schemas/Amount'
              status:
                type: string
                enum:
                  - SETTLED
                  - NOT-SETTLED
              reference_no:
                type: string
              error:
                $ref: '#/components/schemas/Error'
    Settlement:
      description: >
        - Describes the settlement of NP -NP - Describes the miscellaneous
        settlement - Describes the NIL settlement
      type: object
      properties:
        type:
          description: Describes the type of the settlement
          type: string
        id:
          description: |
            * settlement id of the settlement file
          type: string
        order:
          $ref: '#/components/schemas/Orders'
x-enum:
  settle: null
  message:
    settlement:
      type:
        - code: NP-NP
          description: .
          reference: <PR/Issue/Discussion Links md format text
        - code: MICS
          description: .
          reference: <PR/Issue/Discussion Links md format text
        - code: Nill
          description: .
          reference: <PR/Issue/Discussion Links md format text
      order:
        inter_participant: null
x-flows:
  - summary: RSF_NP-NP
    details:
      - description: detailed flow of RSF NP to NP
        mermaid: |-
          sequenceDiagram
           participant Collector
            participant Settlement_Agency
           participant Receiver
           Collector ->> Settlement_Agency: settle API 
           Receiver ->> Settlement_Agency: settle API
           Settlement_Agency ->> Collector : on_setttle API
           Settlement_Agency ->> Receiver : on_setttle API
    references: if any
    steps:
      - summary: SETTLE
        api: settle
        details:
          - description: issue request creating a complaint
            mermaid: |-
              sequenceDiagram participant Collector
               participant Settlement_Agency
               participant Receiver
               Collector ->> Settlement_Agency: settle API 
               Receiver ->> Settlement_Agency: settle API
               Settlement_Agency ->> Collector : on_setttle API
               Settlement_Agency ->> Receiver : on_setttle API
        reference: if any
        example:
          value: &ref_0
            context:
              domain: ONDC:NTS10
              location:
                country:
                  code: IND
                city:
                  code: '*'
              version: 2.0.0
              action: settle
              bap_id: collectorapp.com
              bap_uri: https://collectorapp.com/ondc/1.0/
              bpp_id: sa_nocs.nbbl.com
              bpp_uri: https://abc.nbbl.in/nocs_test
              transaction_id: bd73a366-aebb-4144-9314-808dda82c7e6
              message_id: 941ef6d7-d74d-4411-ac06-a05469c0f9ac
              timestamp: '2024-05-07T06:36:51.897Z'
              ttl: PT30S
            message:
              collector_app_id: collectorapp.com
              receiver_app_id: receiver.com
              settlement:
                type: NP-NP
                id: settlement-id-123
                orders:
                  - id: order-id-456
                    inter_participant:
                      currency: INR
                      value: '1000.00'
                    collector:
                      currency: INR
                      value: '950.00'
                    provider:
                      id: provider-id-789
                      name: Provider Name
                      account_no: '1234567890'
                      ifsc_code: IFSC0001
                      currency: INR
                      value: '900.00'
                    self:
                      currency: INR
                      value: '50.00'
      - summary: ON_SETTLE
        api: on_settle
        details:
          - description: on_settle
            mermaid: |-
              sequenceDiagram participant Collector
               participant Settlement_Agency
               participant Receiver
               Collector ->> Settlement_Agency: settle API 
               Receiver ->> Settlement_Agency: settle API
               Settlement_Agency ->> Collector : on_setttle API
               Settlement_Agency ->> Receiver : on_setttle API
        reference: if any
        example:
          value: &ref_1
            context:
              domain: ONDC:NTS10
              location:
                country:
                  code: IND
                city:
                  code: '*'
              version: 2.0.0
              action: on_settle
              bap_id: collectorapp.com
              bap_uri: https://collectorapp.in/ondc/1.0/
              bpp_id: sa_nocs.nbbl.com
              bpp_uri: https://ondcnbbl.abc.org.in/nocs_test
              transaction_id: bd73a366-aebb-4144-9314-808dda82c7e6
              message_id: 941ef6d7-d74d-4411-ac06-a05469c0f9ac
              timestamp: '2024-05-07T06:36:51.897Z'
              ttl: PT30S
            message:
              collector_app_id: collectorapp.in
              receiver_app_id: receiverapp.com
              settlement:
                type: NP-NP
                id: settlement-id-123
                orders:
                  - id: order-id-456
                    inter_participant:
                      currency: INR
                      value: '50'
                      status: SETTLED
                      reference_no: '3718683618631'
                    collector:
                      currency: INR
                      value: '950.00'
                    provider:
                      id: provider-id-789
                      currency: INR
                      value: '900.00'
                      status: NOT-SETTLED
                      error_code: '01'
                      error_message: Account inactive
                    self:
                      currency: INR
                      value: '50.00'
                      status: NOT-SETTLED
                      error_code: '01'
                      error_message: Account inactive
  - summary: RSF_MICS
    details:
      - description: detailed misc flow
        mermaid: |-
          sequenceDiagram
              participant Collector
               participant Settlement_Agency
               Collector ->> Settlement_Agency: settle API 
               Settlement_Agency ->> Collector : on_setttle API
    references: if any
    steps:
      - summary: SETTLE
        api: settle
        details:
          - description: settle request
            mermaid: |-
              sequenceDiagram participant Collector
               participant Settlement_Agency
               Collector ->> Settlement_Agency: settle API 
               Settlement_Agency ->> Collector : on_setttle API
        reference: if any
        example:
          value:
            context:
              domain: ONDC:NTS10
              location:
                country:
                  code: IND
                city:
                  code: '*'
              version: 2.0.0
              action: settle
              bap_id: collector.com
              bap_uri: https://collector.com/ondc/1.0/
              bpp_id: sa_nocs.nbbl.com
              bpp_uri: https://nbbl.org.in/nocs_test
              transaction_id: bd73a366-aebb-4144-9314-808dda82c7e6
              message_id: 941ef6d7-d74d-4411-ac06-a05469c0f9ac
              timestamp: '2024-05-07T06:36:51.897Z'
              ttl: PT30S
            message:
              collector_app_id: collectorap.com
              receiver_app_id: receiverapp.com
              settlement:
                type: Misc
                id: 941ef6d7-d74d-4411
                orders:
                  - self:
                      currency: INR
                      value: '1000'
                    provider:
                      id: abdccsgg
                      name: RAVI
                      account_no: '0112345678'
                      ifsc_code: ' SBIN0005943'
                      currency: INR
                      value: '1000'
      - summary: ON_SETTLE
        api: on_settle
        details:
          - description: on_settle
            mermaid: |-
              sequenceDiagram participant Collector
               participant Settlement_Agency
               Collector ->> Settlement_Agency: settle API 
               Settlement_Agency ->> Collector : on_setttle API
        reference: if any
        example:
          value:
            context:
              domain: ONDC:NTS10
              location:
                country:
                  code: IND
                city:
                  code: '*'
              version: 2.0.0
              action: on_settle
              bap_id: collectorapp.com
              bap_uri: https://collectorapp.in/ondc/1.0/
              bpp_id: sa_nocs.nbbl.com
              bpp_uri: https://ondcnbbl.abc.org.in/nocs_test
              transaction_id: bd73a366-aebb-4144-9314-808dda82c7e6
              message_id: 941ef6d7-d74d-4411-ac06-a05469c0f9ac
              timestamp: '2024-05-07T06:36:51.897Z'
              ttl: PT30S
            message:
              collector_app_id: collectorapp.com
              receiver_app_id: receiverapp.com
              settlement:
                type: MISC
                id: settlement-id-123
                orders:
                  - id: order-id-456
                    provider:
                      id: provider-id-789
                      currency: INR
                      value: '900.00'
                      status: NOT-SETTLED
                      reference_no: '3718683618631'
                      error_code: '01'
                      error_message: Account inactive
                    self:
                      currency: INR
                      value: '50.00'
                      status: NOT-SETTLED
                      reference_no: '3718683618631'
                      error_code: '01'
                      error_message: Account inactive
  - summary: RSF_NIL
    details:
      - description: detailed flow of RSF (NULL FLOW)
        mermaid: |-
          sequenceDiagram
           participant Collector
           participant Settlement_Agency
           Collector ->> Settlement_Agency: settle API 
           Settlement_Agency ->> Collector : on_setttle API
           participant Receiver
           participant Settlement_Agency
           Receiver ->> Settlement_Agency: settle API 
           Settlement_Agency ->> Receiver : on_setttle API
    references: if any
    steps:
      - summary: SETTLE
        api: settle
        details:
          - description: settle api
            mermaid: |-
              sequenceDiagram participant Collector
               participant Settlement_Agency
               Collector ->> Settlement_Agency: settle API 
               Settlement_Agency ->> Collector : on_setttle API
        reference: if any
        example:
          value:
            context:
              domain: ONDC:NTS10
              location:
                country:
                  code: IND
                city:
                  code: '*'
              version: 2.0.0
              action: settle
              bap_id: collectorapp.com
              bap_uri: https://collector.in/ondc/1.0/
              bpp_id: sa_nocs.nbbl.com
              bpp_uri: https://abc.nbbl.org.in/nocs_test
              transaction_id: bd73a366-aebb-4144-9314-808dda82c7e6
              message_id: 941ef6d7-d74d-4411-ac06-a05469c0f9ac
              timestamp: '2024-05-07T06:36:51.897Z'
              ttl: PT30S
            message:
              settlement:
                type: NIL
      - summary: ON_SETTLE
        api: on_settle
        details:
          - description: on_settle
            mermaid: |-
              sequenceDiagram participant Collector
               participant Settlement_Agency
               Collector ->> Settlement_Agency: settle API 
               Settlement_Agency ->> Collector : on_setttle API
        reference: if any
        example:
          value:
            context:
              domain: ONDC:NTS10
              location:
                country:
                  code: IND
                city:
                  code: '*'
              version: 2.0.0
              action: on_settle
              bap_id: collectorapp.com
              bap_uri: https://beta.abc.in/ondc/1.0/
              bpp_id: sa_nocs.nbbl.com
              bpp_uri: https://abc.nbbl.org.in/nocs_test
              transaction_id: bd73a366-aebb-4144-9314-808dda82c7e6
              message_id: 941ef6d7-d74d-4411-ac06-a05469c0f9ac
              timestamp: '2024-05-07T06:36:51.897Z'
              ttl: PT30S
            message:
              collector_app_id: collector.mystore.in
              receiver_app_id: receiver.sellerapp.com
              settlement:
                type: NIL
                id: settlement-id-123
                orders:
                  - id: order-id-456
                    inter_participant:
                      currency: INR
                      value: '1000.00'
                      status: SETTLED
                      reference_no: '3718683618631'
                      error_code: '01'
                      error_message: Account inactive
                    collector:
                      currency: INR
                      value: '950.00'
                    provider:
                      id: provider-id-789
                      currency: INR
                      value: '900.00'
                      status: NOT-SETTLED
                      reference_no: '3718683618631'
                      error_code: '01'
                      error_message: Account inactive
                    self:
                      currency: INR
                      value: '50.00'
                      status: NOT-SETTLED
                      reference_no: '3718683618631'
                      error_code: '01'
                      error_message: Account inactive
x-examples:
  RSF:
    summary: RSF implementation
    description: RSF implementation
    example_set:
      settle:
        examples:
          - summary: settle
            value: *ref_0
      on_settle:
        examples:
          - summary: on_settle
            value: *ref_1
x-attributes:
  RSF:
    attribute_set:
      on_report:
        context:
          domain:
            required: false
            type: string
            owner: any
            usage: ONDC:NTS10
          location:
            country:
              code:
                required: false
                type: string
                owner: any
                usage: IND
            city:
              code:
                required: false
                type: string
                owner: any
                usage: '*'
          version:
            required: false
            type: string
            owner: any
            usage: 2.0.0
          action:
            required: false
            type: string
            owner: any
            usage: on_report
          bap_id:
            required: false
            type: string
            owner: any
            usage: beta.mystore.in
          bap_uri:
            required: false
            type: string
            owner: any
            usage: https://beta.mystore.in/ondc/1.0/
          bpp_id:
            required: false
            type: string
            owner: any
            usage: sa_nocs.nbbl.com
          bpp_uri:
            required: false
            type: string
            owner: any
            usage: https://ondcnbbl.npci.org.in/nocs_test
          transaction_id:
            required: false
            type: string
            owner: any
            usage: bd73a366-aebb-4144-9314-808dda82c7e6
          message_id:
            required: false
            type: string
            owner: any
            usage: 941ef6d7-d74d-4411-ac06-a05469c0f9ac
          timestamp:
            required: false
            type: string
            owner: any
            usage: '2024-05-07T06:36:51.897Z'
          ttl:
            required: false
            type: string
            owner: any
            usage: PT30S
        message:
          collector_app_id:
            required: false
            type: string
            owner: any
            usage: false
          receiver_app_id:
            required: false
            type: string
            owner: any
            usage: false
          settlement:
            type:
              required: false
              type: string
              owner: any
              usage: NP-NP
            id:
              required: false
              type: string
              owner: any
              usage: false
            orders:
              id:
                required: false
                type: string
                owner: any
                usage: false
              inter_participant:
                currency:
                  required: false
                  type: string
                  owner: any
                  usage: INR
                value:
                  required: false
                  type: string
                  owner: any
                  usage: false
                status:
                  required: false
                  type: string
                  owner: any
                  usage: SETTLED
                reference_no:
                  required: false
                  type: string
                  owner: any
                  usage: '3718683618631'
                error_code:
                  required: false
                  type: string
                  owner: any
                  usage: '01'
                error_message:
                  required: false
                  type: string
                  owner: any
                  usage: Account inactive
              collector:
                currency:
                  required: false
                  type: string
                  owner: any
                  usage: INR
                value:
                  required: false
                  type: string
                  owner: any
                  usage: false
              provider:
                id:
                  required: false
                  type: string
                  owner: any
                  usage: false
                currency:
                  required: false
                  type: string
                  owner: any
                  usage: false
                value:
                  required: false
                  type: string
                  owner: any
                  usage: false
                status:
                  required: false
                  type: string
                  owner: any
                  usage: NOT-SETTLED
                reference_no:
                  required: false
                  type: string
                  owner: any
                  usage: '3718683618631'
                error_code:
                  required: false
                  type: string
                  owner: any
                  usage: '01'
                error_message:
                  required: false
                  type: string
                  owner: any
                  usage: Account inactive
              self:
                currency:
                  required: false
                  type: string
                  owner: any
                  usage: false
                value:
                  required: false
                  type: string
                  owner: any
                  usage: false
                status:
                  required: false
                  type: string
                  owner: any
                  usage: false
                reference_no:
                  required: false
                  type: string
                  owner: any
                  usage: '3718683618631'
                error_code:
                  required: false
                  type: string
                  owner: any
                  usage: '01'
                error_message:
                  required: false
                  type: string
                  owner: any
                  usage: Account inactive
      on_settle:
        context:
          domain:
            required: false
            type: string
            owner: any
            usage: ONDC:NTS10
          location:
            country:
              code:
                required: false
                type: string
                owner: any
                usage: IND
            city:
              code:
                required: false
                type: string
                owner: any
                usage: '*'
          version:
            required: false
            type: string
            owner: any
            usage: 2.0.0
          action:
            required: false
            type: string
            owner: any
            usage: on_settle
          bap_id:
            required: false
            type: string
            owner: any
            usage: beta.mystore.in
          bap_uri:
            required: false
            type: string
            owner: any
            usage: https://beta.mystore.in/ondc/1.0/
          bpp_id:
            required: false
            type: string
            owner: any
            usage: sa_nocs.nbbl.com
          bpp_uri:
            required: false
            type: string
            owner: any
            usage: https://ondcnbbl.npci.org.in/nocs_test
          transaction_id:
            required: false
            type: string
            owner: any
            usage: bd73a366-aebb-4144-9314-808dda82c7e6
          message_id:
            required: false
            type: string
            owner: any
            usage: 941ef6d7-d74d-4411-ac06-a05469c0f9ac
          timestamp:
            required: false
            type: string
            owner: any
            usage: '2024-05-07T06:36:51.897Z'
          ttl:
            required: false
            type: string
            owner: any
            usage: PT30S
        message:
          collector_app_id:
            required: false
            type: string
            owner: any
            usage: false
          receiver_app_id:
            required: false
            type: string
            owner: any
            usage: false
          settlement:
            type:
              required: false
              type: string
              owner: any
              usage: NP-NP
            id:
              required: false
              type: string
              owner: any
              usage: false
            orders:
              id:
                required: false
                type: string
                owner: any
                usage: false
              inter_participant:
                currency:
                  required: false
                  type: string
                  owner: any
                  usage: INR
                value:
                  required: false
                  type: string
                  owner: any
                  usage: false
                status:
                  required: false
                  type: string
                  owner: any
                  usage: SETTLED
                reference_no:
                  required: false
                  type: string
                  owner: any
                  usage: '3718683618631'
                error_code:
                  required: false
                  type: string
                  owner: any
                  usage: '01'
                error_message:
                  required: false
                  type: string
                  owner: any
                  usage: Account inactive
              collector:
                currency:
                  required: false
                  type: string
                  owner: any
                  usage: INR
                value:
                  required: false
                  type: string
                  owner: any
                  usage: false
              provider:
                id:
                  required: false
                  type: string
                  owner: any
                  usage: false
                currency:
                  required: false
                  type: string
                  owner: any
                  usage: false
                value:
                  required: false
                  type: string
                  owner: any
                  usage: false
                status:
                  required: false
                  type: string
                  owner: any
                  usage: NOT-SETTLED
                reference_no:
                  required: false
                  type: string
                  owner: any
                  usage: '3718683618631'
                error_code:
                  required: false
                  type: string
                  owner: any
                  usage: '01'
                error_message:
                  required: false
                  type: string
                  owner: any
                  usage: Account inactive
              self:
                currency:
                  required: false
                  type: string
                  owner: any
                  usage: false
                value:
                  required: false
                  type: string
                  owner: any
                  usage: false
                status:
                  required: false
                  type: string
                  owner: any
                  usage: false
                reference_no:
                  required: false
                  type: string
                  owner: any
                  usage: '3718683618631'
                error_code:
                  required: false
                  type: string
                  owner: any
                  usage: '01'
                error_message:
                  required: false
                  type: string
                  owner: any
                  usage: Account inactive
      report:
        context:
          domain:
            required: false
            type: string
            owner: any
            usage: ONDC:NTS10
          location:
            country:
              code:
                required: false
                type: string
                owner: any
                usage: IND
            city:
              code:
                required: false
                type: string
                owner: any
                usage: '*'
          version:
            required: false
            type: string
            owner: any
            usage: 2.0.0
          action:
            required: false
            type: string
            owner: any
            usage: report
          bap_id:
            required: false
            type: string
            owner: any
            usage: buyerapp.com
          bap_uri:
            required: false
            type: string
            owner: any
            usage: https://buyerapp.com/ondc/1.0/
          bpp_id:
            required: false
            type: string
            owner: any
            usage: sa_nocs.nbbl.com
          bpp_uri:
            required: false
            type: string
            owner: any
            usage: https://ondcnbbl.npci.org.in/nocs_test
          transaction_id:
            required: false
            type: string
            owner: any
            usage: bd73a366-aebb-4144-9314-808dda82c7e6
          message_id:
            required: false
            type: string
            owner: any
            usage: 941ef6d7-d74d-4411-ac06-a05469c0f9ac
          timestamp:
            required: false
            type: string
            owner: any
            usage: '2024-05-07T06:36:51.897Z'
          ttl:
            required: false
            type: string
            owner: any
            usage: PT30S
        message:
          ref_transaction_id:
            required: false
            type: string
            owner: any
            usage: false
          ref_message_id:
            required: false
            type: string
            owner: any
            usage: false
      settle_misc:
        context:
          domain:
            required: false
            type: string
            owner: any
            usage: ONDC:NTS10
          location:
            country:
              code:
                required: false
                type: string
                owner: any
                usage: IND
            city:
              code:
                required: false
                type: string
                owner: any
                usage: '*'
          version:
            required: false
            type: string
            owner: any
            usage: 2.0.0
          action:
            required: false
            type: string
            owner: any
            usage: settle
          bap_id:
            required: false
            type: string
            owner: any
            usage: buyerapp.com
          bap_uri:
            required: false
            type: string
            owner: any
            usage: https://buyerapp.com/ondc/1.0/
          bpp_id:
            required: false
            type: string
            owner: any
            usage: sa_nocs.nbbl.com
          bpp_uri:
            required: false
            type: string
            owner: any
            usage: https://ondcnbbl.npci.org.in/nocs_test
          transaction_id:
            required: false
            type: string
            owner: any
            usage: bd73a366-aebb-4144-9314-808dda82c7e6
          message_id:
            required: false
            type: string
            owner: any
            usage: 941ef6d7-d74d-4411-ac06-a05469c0f9ac
          timestamp:
            required: false
            type: string
            owner: any
            usage: '2024-05-07T06:36:51.897Z'
          ttl:
            required: false
            type: string
            owner: any
            usage: PT30S
        message:
          collector_app_id:
            required: false
            type: string
            owner: any
            usage: buyerapp.com
          receiver_app_id:
            required: false
            type: string
            owner: any
            usage: false
          settlement:
            type:
              required: false
              type: string
              owner: any
              usage: Misc
            id:
              required: false
              type: string
              owner: any
              usage: false
            orders:
              self:
                currency:
                  required: false
                  type: string
                  owner: any
                  usage: false
                value:
                  required: false
                  type: string
                  owner: any
                  usage: false
              provider:
                id:
                  required: false
                  type: string
                  owner: any
                  usage: false
                name:
                  required: false
                  type: string
                  owner: any
                  usage: false
                account_no:
                  required: false
                  type: string
                  owner: any
                  usage: false
                ifsc_code:
                  required: false
                  type: string
                  owner: any
                  usage: false
                currency:
                  required: false
                  type: string
                  owner: any
                  usage: false
                value:
                  required: false
                  type: string
                  owner: any
                  usage: false
      settle_np-np:
        context:
          domain:
            required: false
            type: string
            owner: any
            usage: ONDC:NTS10
          location:
            country:
              code:
                required: false
                type: string
                owner: any
                usage: IND
            city:
              code:
                required: false
                type: string
                owner: any
                usage: '*'
          version:
            required: false
            type: string
            owner: any
            usage: 2.0.0
          action:
            required: false
            type: string
            owner: any
            usage: settle
          bap_id:
            required: false
            type: string
            owner: any
            usage: buyerapp.com
          bap_uri:
            required: false
            type: string
            owner: any
            usage: https://buyerapp.com/ondc/1.0/
          bpp_id:
            required: false
            type: string
            owner: any
            usage: sa_nocs.nbbl.com
          bpp_uri:
            required: false
            type: string
            owner: any
            usage: https://ondcnbbl.npci.org.in/nocs_test
          transaction_id:
            required: false
            type: string
            owner: any
            usage: bd73a366-aebb-4144-9314-808dda82c7e6
          message_id:
            required: false
            type: string
            owner: any
            usage: 941ef6d7-d74d-4411-ac06-a05469c0f9ac
          timestamp:
            required: false
            type: string
            owner: any
            usage: '2024-05-07T06:36:51.897Z'
          ttl:
            required: false
            type: string
            owner: any
            usage: PT30S
        message:
          collector_app_id:
            required: false
            type: string
            owner: any
            usage: false
          receiver_app_id:
            required: false
            type: string
            owner: any
            usage: false
          settlement:
            type:
              required: false
              type: string
              owner: any
              usage: NP-NP
            id:
              required: false
              type: string
              owner: any
              usage: false
            orders:
              id:
                required: false
                type: string
                owner: any
                usage: false
              inter_participant:
                currency:
                  required: false
                  type: string
                  owner: any
                  usage: INR
                value:
                  required: false
                  type: string
                  owner: any
                  usage: false
              collector:
                currency:
                  required: false
                  type: string
                  owner: any
                  usage: INR
                value:
                  required: false
                  type: string
                  owner: any
                  usage: false
              provider:
                id:
                  required: false
                  type: string
                  owner: any
                  usage: false
                name:
                  required: false
                  type: string
                  owner: any
                  usage: false
                account_no:
                  required: false
                  type: string
                  owner: any
                  usage: false
                ifsc_code:
                  required: false
                  type: string
                  owner: any
                  usage: false
                currency:
                  required: false
                  type: string
                  owner: any
                  usage: false
                value:
                  required: false
                  type: string
                  owner: any
                  usage: false
              self:
                currency:
                  required: false
                  type: string
                  owner: any
                  usage: false
                value:
                  required: false
                  type: string
                  owner: any
                  usage: false
      settle_null_file:
        context:
          domain:
            required: false
            type: string
            owner: any
            usage: ONDC:NTS10
          location:
            country:
              code:
                required: false
                type: string
                owner: any
                usage: IND
            city:
              code:
                required: false
                type: string
                owner: any
                usage: '*'
          version:
            required: false
            type: string
            owner: any
            usage: 2.0.0
          action:
            required: false
            type: string
            owner: any
            usage: settle
          bap_id:
            required: false
            type: string
            owner: any
            usage: buyerapp.com
          bap_uri:
            required: false
            type: string
            owner: any
            usage: https://buyerapp.in/ondc/1.0/
          bpp_id:
            required: false
            type: string
            owner: any
            usage: sa_nocs.nbbl.com
          bpp_uri:
            required: false
            type: string
            owner: any
            usage: https://ondcnbbl.npci.org.in/nocs_test
          transaction_id:
            required: false
            type: string
            owner: any
            usage: bd73a366-aebb-4144-9314-808dda82c7e6
          message_id:
            required: false
            type: string
            owner: any
            usage: 941ef6d7-d74d-4411-ac06-a05469c0f9ac
          timestamp:
            required: false
            type: string
            owner: any
            usage: '2024-05-07T06:36:51.897Z'
          ttl:
            required: false
            type: string
            owner: any
            usage: PT30S
        message:
          settlement:
            type:
              required: false
              type: string
              owner: any
              usage: '0'
